import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";
const allowedOrigins=new Set(["https://weisheng-underwear-web.vercel.app","https://weisheng-underwear-live-bensondrum.vercel.app"]);allowedOrigins.add("https://weisheng-underwear.vercel.app");
function cors(origin:string|null){const fallback="https://weisheng-underwear-web.vercel.app";const allow=origin&&allowedOrigins.has(origin)?origin:fallback;return{"Access-Control-Allow-Origin":allow,"Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS","Vary":"Origin","Content-Type":"application/json; charset=utf-8"};}
async function sendLineNotification(db:any,orderNo:string,customerName:string,sourceName:string,delivery:string,count:number,total:number){try{const token=Deno.env.get("LINE_CHANNEL_ACCESS_TOKEN")||"";if(!token){console.error("LINE notification skipped: token missing");return;}const{data:recipients,error}=await db.from("line_notification_recipients").select("user_id").eq("active",true);if(error){console.error("LINE recipients lookup failed",error);return;}if(!recipients?.length)return;const text=`🔔 偉聖內衣｜新訂單通知\n訂單：${orderNo}\n客戶：${customerName}\n來源：${sourceName}\n配送：${delivery}\n數量：${count} 件\n金額：NT$ ${Number(total).toLocaleString("en-US")}\n\n新訂單已進入後台，請確認處理。`;for(const r of recipients){try{const res=await fetch("https://api.line.me/v2/bot/message/push",{method:"POST",headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json"},body:JSON.stringify({to:r.user_id,messages:[{type:"text",text}]})});if(!res.ok)console.error("LINE push failed",res.status,await res.text());}catch(err){console.error("LINE push exception",err);}}}catch(err){console.error("LINE notification error",err);}}
// Confirmed fixed-price launch SKUs; all other products retain their group discount.
const FIXED_PRICE_SKUS=new Set(["A3359-BLUE","A3359-PINK","A3359-YELLOW","K6235-3","K6435-62","K6435-63","K9034-62","K9034-66","K9135-2","K9336-4","PB205-BLACK","PB205-BLUE","PB206-BLACK","PB206-GREEN","PB207-BLUE","PB207-GRAY","PB2320-DARK","PB2320-GRAY","PB2325-DARK","PB2325-GRAY"]);
Deno.serve(async(req:Request)=>{const origin=req.headers.get("origin");const headers=cors(origin);if(req.method==="OPTIONS")return new Response("ok",{headers});if(req.method!=="POST")return new Response(JSON.stringify({error:"method_not_allowed"}),{status:405,headers});if(!origin||!allowedOrigins.has(origin))return new Response(JSON.stringify({error:"origin_not_allowed"}),{status:403,headers});try{const body=await req.json();const customerName=String(body.customer_name||"").trim();const customerContact=String(body.customer_contact??"").trim();if(customerContact.length>200)throw new Error("invalid_customer_contact");const sourceKey=String(body.source_key||"general").trim()||"general";const delivery=String(body.delivery||"業務配送").trim();const items=Array.isArray(body.items)?body.items:[];if(!customerName||customerName.length>100)throw new Error("invalid_customer_name");if(!items.length||items.length>200)throw new Error("invalid_items");if(!["業務配送","郵寄"].includes(delivery))throw new Error("invalid_delivery");const db=createClient(Deno.env.get("SUPABASE_URL")!,Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,{auth:{persistSession:false}});
let discountRate=1,sourceName="一般客戶";if(sourceKey!=="general"){const{data:g,error:ge}=await db.from("group_configs").select("name,discount_rate,active,ends_at").eq("group_key",sourceKey).single();const expired=!!g?.ends_at&&new Date(g.ends_at).getTime()<=Date.now();if(ge||!g||!g.active||expired)throw new Error(expired?"group_expired":"invalid_or_inactive_group");discountRate=Number(g.discount_rate);sourceName=String(g.name);if(delivery!=="業務配送")throw new Error("group_delivery_must_be_business");}
// Enforce the group restriction before any order or notification is created.
if(sourceKey==='group-兒童村內褲團購'&&items.some((x:any)=>String(x.sku||x.id||'').trim()==='P142211'&&String(x.size||'').trim()==='22'))throw new Error('insufficient_stock:P142211:22');
const skus=[...new Set(items.map((x:any)=>String(x.sku||x.id||"").trim()).filter(Boolean))];const{data:products,error:pe}=await db.from("catalog_products").select("sku,brand,product_name,active").in("sku",skus);if(pe)throw pe;const{data:variants,error:ve}=await db.from("catalog_variants").select("sku,size,base_price,active").in("sku",skus);if(ve)throw ve;const pmap=new Map((products||[]).map((p:any)=>[p.sku,p]));const vmap=new Map((variants||[]).map((v:any)=>[`${v.sku}::${v.size}`,v]));
const cleanItems=items.map((x:any)=>{const sku=String(x.sku||x.id||"").trim(),size=String(x.size||"").trim(),qty=Number(x.qty);if(!sku||!size||!Number.isInteger(qty)||qty<=0||qty>999)throw new Error("invalid_item");const p:any=pmap.get(sku),v:any=vmap.get(`${sku}::${size}`);if(!p||!p.active)throw new Error(`invalid_sku:${sku}`);if(!v||!v.active)throw new Error(`invalid_size:${sku}:${size}`);const unitPrice=Math.round(Number(v.base_price)*(FIXED_PRICE_SKUS.has(sku)?1:discountRate));const sent=Number(x.unit_price??x.price);if(!Number.isInteger(sent)||sent!==unitPrice)throw new Error(`invalid_price:${sku}:${size}`);return{sku,brand:p.brand,product_name:p.product_name,size,qty,unit_price:unitPrice,line_total:qty*unitPrice};});
const total=cleanItems.reduce((a:number,x:any)=>a+x.line_total,0),count=cleanItems.reduce((a:number,x:any)=>a+x.qty,0);if(delivery==="郵寄"&&total<4000)throw new Error("postal_minimum_not_met");const orderNo=`WS${new Date().toISOString().replace(/\D/g,"").slice(0,17)}${Math.floor(Math.random()*900+100)}`;const{data:result,error:re}=await db.rpc('create_order_with_contact',{p_order_no:orderNo,p_source_key:sourceKey,p_source_name:sourceName,p_discount_rate:discountRate,p_customer_name:customerName,p_customer_contact:customerContact,p_delivery:delivery,p_total:total,p_item_count:count,p_items:cleanItems});if(re)throw re;const finalOrderNo=result?.order_no||orderNo,finalTotal=result?.total??total,finalCount=result?.count??count;await sendLineNotification(db,finalOrderNo,customerName,sourceName,delivery,finalCount,finalTotal);return new Response(JSON.stringify({success:true,order_no:finalOrderNo,total:finalTotal,count:finalCount}),{status:200,headers});}catch(e){console.error(e);const msg=e instanceof Error?e.message:"submit_failed";return new Response(JSON.stringify({success:false,error:msg}),{status:400,headers});}});
